package Tplogs;


/**
* Tplogs/Log.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tplogs.idl
* den 16 maj 2016 kl 22:48 CEST
*/

public final class Log implements org.omg.CORBA.portable.IDLEntity
{
  public String lan = null;

  // NUM LAN
  public String ID = null;

  // ID PC
  public String date = null;

  //DATE
  public String body = null;

  public Log ()
  {
  } // ctor

  public Log (String _lan, String _ID, String _date, String _body)
  {
    lan = _lan;
    ID = _ID;
    date = _date;
    body = _body;
  } // ctor

} // class Log
