package Tplogs;

/**
* Tplogs/LogHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tplogs.idl
* den 16 maj 2016 kl 22:48 CEST
*/

public final class LogHolder implements org.omg.CORBA.portable.Streamable
{
  public Tplogs.Log value = null;

  public LogHolder ()
  {
  }

  public LogHolder (Tplogs.Log initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Tplogs.LogHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Tplogs.LogHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Tplogs.LogHelper.type ();
  }

}
