package Tplogs;


/**
* Tplogs/TplogsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tplogs.idl
* den 16 maj 2016 kl 22:48 CEST
*/

public interface TplogsOperations 
{
  void writeToMainLog ();

  //Dont really the parameters, do we send the file? so we write through a stream?
  boolean isMainLogAvailable ();
  void iAmWritingToMainLog ();
  boolean canIWriteToMainLog ();

  //
  boolean mainLogIsFree ();
} // interface TplogsOperations
