package Tplogs;

/**
* Tplogs/TplogsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tplogs.idl
* den 16 maj 2016 kl 22:48 CEST
*/

public final class TplogsHolder implements org.omg.CORBA.portable.Streamable
{
  public Tplogs.Tplogs value = null;

  public TplogsHolder ()
  {
  }

  public TplogsHolder (Tplogs.Tplogs initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Tplogs.TplogsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Tplogs.TplogsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Tplogs.TplogsHelper.type ();
  }

}
